name: windowd10RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/roshan-iolite/windowd10RDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/roshan-iolite/windowd10RDP/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/roshan-iolite/windowd10RDP/main/loop.bat -OutFile loop.bat
    - name: Windows10 RDP.
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Connect RDP.
      run: |
        cmd /c start.bat
        $ip =  Invoke-WebRequest ifconfig.me/ip -UseBasicParsing
        $ip.Content
    - name: win10 RDP.
      run: cmd /c loop.bat
